### ISSUE TITLE
Windows Active Directory Authentication

### ISSUE THREAD

**Issue by Sima-G** [lucianw/ldap-jwt#11]
The authentication works great with generic LDAP. But when I have to manage to connect with Active Directory I am getting this error: OperationsError: 000004DC: LdapErr: DSID-0C090A22

**Comment by lucianweber** [comment]
This looks like a problem with the underlying [jwt-simple](https://github.com/hokaccha/node-jwt-simple) library since this project is not implementing the LDAP protocol itself.
If the problem is still persistent, please check with that project and consider reopening the issue there.
